import '../models/product.dart';
import '../models/advisor.dart';

class DataService {
  static List<Product> getSampleProducts() {
    return [
      Product(
        id: 'p1',
        name: '행운의 붉은 부적',
        description: '액운을 막고 행운을 불러오는 전통 부적입니다. 사주 분석 결과에 따라 맞춤 제작됩니다.',
        price: 15000,
        category: '부적',
        imageUrls: ['https://via.placeholder.com/300x400/ff0000/ffffff?text=Red+Amulet'],
        attributes: {
          'type': '행운',
          'material': '한지, 주사',
          'size': '10cm x 15cm',
        },
        stockCount: 50,
        rating: 4.8,
        reviewCount: 127,
        createdAt: DateTime.now().subtract(const Duration(days: 30)),
      ),
      Product(
        id: 'p2',
        name: '재물운 황금 부적',
        description: '재물운을 높이고 사업 번창을 기원하는 황금색 부적입니다.',
        price: 20000,
        category: '부적',
        imageUrls: ['https://via.placeholder.com/300x400/ffd700/000000?text=Gold+Amulet'],
        attributes: {
          'type': '재물',
          'material': '한지, 금가루',
          'size': '10cm x 15cm',
        },
        stockCount: 35,
        rating: 4.9,
        reviewCount: 93,
        createdAt: DateTime.now().subtract(const Duration(days: 25)),
      ),
      Product(
        id: 'p3',
        name: '애정운 분홍 부적',
        description: '좋은 인연을 만나고 사랑을 이루는데 도움을 주는 분홍색 부적입니다.',
        price: 18000,
        category: '부적',
        imageUrls: ['https://via.placeholder.com/300x400/ff69b4/ffffff?text=Pink+Amulet'],
        attributes: {
          'type': '애정',
          'material': '한지, 분홍 물감',
          'size': '10cm x 15cm',
        },
        stockCount: 42,
        rating: 4.7,
        reviewCount: 156,
        createdAt: DateTime.now().subtract(const Duration(days: 20)),
      ),
      Product(
        id: 'p4',
        name: '건강장수 청색 부적',
        description: '건강과 장수를 기원하는 청색 부적으로 병마를 물리칩니다.',
        price: 17000,
        category: '부적',
        imageUrls: ['https://via.placeholder.com/300x400/0000ff/ffffff?text=Blue+Amulet'],
        attributes: {
          'type': '건강',
          'material': '한지, 청색 물감',
          'size': '10cm x 15cm',
        },
        stockCount: 28,
        rating: 4.6,
        reviewCount: 84,
        createdAt: DateTime.now().subtract(const Duration(days: 15)),
      ),
      Product(
        id: 'p5',
        name: '학업성취 녹색 부적',
        description: '학업 성취와 시험 합격을 기원하는 녹색 부적입니다.',
        price: 16000,
        category: '부적',
        imageUrls: ['https://via.placeholder.com/300x400/00ff00/000000?text=Green+Amulet'],
        attributes: {
          'type': '학업',
          'material': '한지, 녹색 물감',
          'size': '10cm x 15cm',
        },
        stockCount: 60,
        rating: 4.8,
        reviewCount: 215,
        createdAt: DateTime.now().subtract(const Duration(days: 10)),
      ),
      Product(
        id: 'p6',
        name: '종합운 오색 부적 세트',
        description: '모든 운을 총망라한 오색 부적 세트입니다. 행운, 재물, 애정, 건강, 학업 부적 포함.',
        price: 75000,
        category: '세트',
        imageUrls: ['https://via.placeholder.com/300x400/ffffff/000000?text=5+Color+Set'],
        attributes: {
          'type': '종합',
          'material': '한지, 오색 물감',
          'size': '10cm x 15cm (5개)',
        },
        stockCount: 15,
        rating: 5.0,
        reviewCount: 48,
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
      ),
      Product(
        id: 'p7',
        name: '수정 팔찌',
        description: '천연 수정으로 만든 팔찌로 나쁜 기운을 막아줍니다.',
        price: 35000,
        category: '악세서리',
        imageUrls: ['https://via.placeholder.com/300x300/cccccc/000000?text=Crystal+Bracelet'],
        attributes: {
          'type': '수정',
          'material': '천연 수정',
          'size': 'Free',
        },
        stockCount: 22,
        rating: 4.5,
        reviewCount: 67,
        createdAt: DateTime.now().subtract(const Duration(days: 12)),
      ),
      Product(
        id: 'p8',
        name: '오방색 노리개',
        description: '전통 오방색으로 만든 노리개로 행운을 불러옵니다.',
        price: 28000,
        category: '악세서리',
        imageUrls: ['https://via.placeholder.com/300x300/ff0000/ffffff?text=5+Color+Norigae'],
        attributes: {
          'type': '노리개',
          'material': '명주실, 구슬',
          'size': '12cm',
        },
        stockCount: 18,
        rating: 4.7,
        reviewCount: 52,
        createdAt: DateTime.now().subtract(const Duration(days: 8)),
      ),
    ];
  }

  static List<Advisor> getSampleAdvisors() {
    return [
      Advisor(
        id: 'a1',
        name: '김명리 선생님',
        profileImageUrl: 'https://via.placeholder.com/200x200/4169e1/ffffff?text=Kim',
        expertise: ['사주팔자', '관상', '작명'],
        introduction: '30년 경력의 사주명리학 전문가입니다. 정확한 분석과 따뜻한 상담으로 많은 분들께 도움을 드리고 있습니다.',
        rating: 4.9,
        consultationCount: 1250,
        pricePerMinute: 3000,
        isAvailable: true,
        createdAt: DateTime.now().subtract(const Duration(days: 1000)),
      ),
      Advisor(
        id: 'a2',
        name: '이타로 선생님',
        profileImageUrl: 'https://via.placeholder.com/200x200/ff69b4/ffffff?text=Lee',
        expertise: ['타로', '연애운', '심리상담'],
        introduction: '타로 마스터로서 15년간 수많은 상담을 진행했습니다. 연애와 인간관계 상담이 특기입니다.',
        rating: 4.8,
        consultationCount: 890,
        pricePerMinute: 2500,
        isAvailable: true,
        createdAt: DateTime.now().subtract(const Duration(days: 800)),
      ),
      Advisor(
        id: 'a3',
        name: '박역학 선생님',
        profileImageUrl: 'https://via.placeholder.com/200x200/32cd32/ffffff?text=Park',
        expertise: ['역학', '풍수지리', '택일'],
        introduction: '전통 역학과 풍수지리를 전공했습니다. 이사, 개업일 등 중요한 날짜 선택에 도움을 드립니다.',
        rating: 4.7,
        consultationCount: 650,
        pricePerMinute: 3500,
        isAvailable: false,
        createdAt: DateTime.now().subtract(const Duration(days: 600)),
      ),
      Advisor(
        id: 'a4',
        name: '최관상 선생님',
        profileImageUrl: 'https://via.placeholder.com/200x200/ffa500/ffffff?text=Choi',
        expertise: ['관상', '손금', '인상학'],
        introduction: '관상과 손금 전문가입니다. 사진만으로도 정확한 분석이 가능합니다.',
        rating: 4.6,
        consultationCount: 720,
        pricePerMinute: 2800,
        isAvailable: true,
        createdAt: DateTime.now().subtract(const Duration(days: 500)),
      ),
      Advisor(
        id: 'a5',
        name: '정심리 선생님',
        profileImageUrl: 'https://via.placeholder.com/200x200/9370db/ffffff?text=Jung',
        expertise: ['심리상담', '타로', '꿈해몽'],
        introduction: '심리학과 타로를 결합한 상담을 진행합니다. 내면의 문제를 함께 풀어갑니다.',
        rating: 4.9,
        consultationCount: 1100,
        pricePerMinute: 3200,
        isAvailable: true,
        createdAt: DateTime.now().subtract(const Duration(days: 700)),
      ),
    ];
  }
}
