import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocalizationService extends ChangeNotifier {
  static const String _languageKey = 'selected_language';
  String _currentLanguage = 'ko'; // Default Korean

  String get currentLanguage => _currentLanguage;

  // Supported languages (6 languages)
  static const List<Map<String, String>> supportedLanguages = [
    {'code': 'ko', 'name': '한국어', 'flag': '🇰🇷'},
    {'code': 'en', 'name': 'English', 'flag': '🇺🇸'},
    {'code': 'ja', 'name': '日本語', 'flag': '🇯🇵'},
    {'code': 'zh', 'name': '中文', 'flag': '🇨🇳'},
    {'code': 'vi', 'name': 'Tiếng Việt', 'flag': '🇻🇳'},
    {'code': 'ar', 'name': 'العربية', 'flag': '🇸🇦'},
  ];

  Future<void> loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString(_languageKey) ?? 'ko';
    notifyListeners();
  }

  Future<void> setLanguage(String languageCode) async {
    _currentLanguage = languageCode;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, languageCode);
    notifyListeners();
  }

  String translate(String key) {
    return _translations[_currentLanguage]?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'ko': {
      'app_title': '✨ 운세의 신, 사주 풀이',
      'home': '홈',
      'my_reports': '내 리포트',
      'shop': '상점',
      'consultation': '상담',
      'ai_analysis': 'AI 분석',
      'daily_fortune': '데일리 운세',
      'personality': '성격 분석',
      'face_reading': '얼굴 관상',
      'face_reading_subtitle': 'AI 얼굴 분석',
      'palm_reading': '손금 분석',
      'palm_reading_subtitle': 'AI 손금 분석',
      'saju': '사주팔자',
      'saju_subtitle': '생년월일 분석',
      'tarot': '타로',
      'tarot_subtitle': '타로 리딩',
      'zodiac': '별자리',
      'zodiac_subtitle': '별자리 운세',
      'mbti': 'MBTI',
      'mbti_subtitle': '성격 유형 분석',
      'today_fortune': '오늘의 운세',
      'today_fortune_subtitle': '데일리 럭키',
      'disclaimer': '※ 본 분석 결과는 참고용이며, 개인의 노력과 선택이 더욱 중요합니다.',
      'promo_title': '🎉 특별 프로모션!',
      'promo_subtitle': '₩48,000원으로 1년',
      'promo_highlight': '',
      'promo_free_trial_line1': '회원가입 없이',
      'promo_free_trial_line2': '2회 무료체험',
      'promo_description': '지금 가입하면 12개월 프리미엄 서비스를\n특별 가격에 이용하실 수 있습니다!',
      'promo_button': '지금 시작하기',
      // Signup
      'signup_cta_title': '회원가입',
      'signup_cta_subtitle': '12개월 프리미엄 서비스 시작하기',
      'signup_title': '회원가입',
      'signup_welcome': '환영합니다!',
      'signup_subtitle': '12개월 프리미엄 서비스를 시작하세요',
      'name_label': '이름',
      'name_hint': '이름을 입력하세요',
      'name_required': '이름을 입력해주세요',
      'gender_label': '성별',
      'male': '남성',
      'female': '여성',
      'birthdate_label': '생년월일 (양력)',
      'birthdate_hint': 'YYYY-MM-DD',
      'birthdate_required': '생년월일을 선택해주세요',
      'email_label': '이메일',
      'email_hint': 'example@email.com',
      'email_required': '이메일을 입력해주세요',
      'email_invalid': '올바른 이메일 형식이 아닙니다',
      'payment_title': '결제 정보',
      'payment_plan': '1년 프리미엄 서비스',
      'payment_price': '₩48,000',
      'select_payment_method': '결제 방법을 선택하세요',
      'bank_transfer': '가상계좌',
      'kakao_pay': '카카오페이',
      'naver_pay': '네이버페이',
      'mobile_payment': '휴대폰',
      'signup_button': '가입하기',
      'select_gender_error': '성별을 선택해주세요',
      'select_payment_error': '결제 방법을 선택해주세요',
      'signup_success_title': '가입 완료!',
      'signup_success_message': '회원가입이 완료되었습니다. 12개월 프리미엄 서비스를 즐기세요!',
      'confirm': '확인',
      'error': '오류',
      'global_service': '🌍 글로벌 서비스',
      'language': '언어',
      // Today Fortune Screen
      'today_fortune_title': '☀️ 오늘의 운세',
      'overall_fortune': '종합 운세',
      'love_fortune': '연애운',
      'money_fortune': '금전운',
      'health_fortune': '건강운',
      'work_fortune': '직장운',
      'todays_luck': '🍀 오늘의 행운',
      'lucky_number': '행운의 숫자',
      'lucky_color': '행운의 색상',
      'lucky_item': '행운의 아이템',
      'todays_advice': '오늘의 조언',
      'refresh': '다시 보기',
      // Zodiac Screen
      'zodiac_title': '⭐ 별자리 운세',
      'select_zodiac': '당신의 별자리를 선택하세요',
      'select_zodiac_desc': '생일을 기준으로 별자리를 찾아보세요',
      'choose_again': '다시 선택',
      'todays_fortune_detail': '오늘의 운세',
      'personality_traits': '성격 특징',
      'lucky_elements': '행운의 요소',
      'lucky_day': '행운의 요일',
      // MBTI Screen
      'mbti_title': '🧠 MBTI 성격 분석',
      'select_mbti': '당신의 MBTI를 선택하세요',
      'select_mbti_desc': '16가지 성격 유형 중 하나를 선택하세요',
      'analysts': '분석가형',
      'diplomats': '외교관형',
      'sentinels': '관리자형',
      'explorers': '탐험가형',
      'description': '성격 설명',
      'traits': '성격 특징',
      'strengths': '강점',
      'career_suggestions': '추천 직업',
      // Face Analysis Screen
      'face_analysis_title': '얼굴 관상 분석',
      'face_analysis_desc': 'AI가 얼굴 사진을 분석하여\n관상을 풀이해드립니다',
      'take_photo': '사진 촬영하기',
      'upload_photo': '사진 업로드',
      'analyzing': '분석 중...',
      // Palm Reading Screen
      'palm_reading_title': '손금 분석',
      'palm_reading_desc': 'AI가 손금 사진을 분석하여\n운명을 풀이해드립니다',
      // Saju Screen
      'saju_title': '사주팔자',
      'saju_desc': '생년월일과 시간을 입력하여\n사주를 확인하세요',
      'birth_date': '생년월일',
      'birth_time': '태어난 시간',
      'gender': '성별',
      'analyze_saju': '사주 분석하기',
      'enter_birth_info': '생년월일을 입력하세요',
      // Tarot Screen
      'tarot_title': '타로 카드',
      'tarot_desc': '질문을 생각하며\n카드를 선택하세요',
      'tarot_reading': '타로 카드 리딩',
      'tarot_reading_desc': '타로 카드로 미래를 읽어보세요',
      'question': '질문',
      'question_placeholder': '예: 나의 연애운은 어떤가요?',
      'enter_question': '질문을 입력해주세요',
      'card_count': '카드 수',
      'one_card': '한 장',
      'three_cards': '세 장',
      'five_cards': '다섯 장',
      'start_reading': '타로 리딩 시작',
      'drawing_cards': '카드를 뽑고 있습니다...',
      'tarot_guide': '타로 리딩 안내',
      'one_card_desc': '간단한 질문에 대한 답',
      'three_cards_desc': '과거-현재-미래 흐름',
      'five_cards_desc': '복잡한 상황 분석',
      'select_cards': '카드 선택하기',
      'card_reading': '카드 해석',
      // Shop Screen
      'category_all': '전체',
      'category_talisman': '부적',
      'category_accessory': '액세서리',
      'category_service': '서비스',
      'product_detail': '상품 상세',
      'product_description': '상품 설명',
      'reviews': '리뷰',
      'add_to_cart': '장바구니 담기',
      'added_to_cart': '장바구니에 담았습니다',
      'view_cart': '보기',
      'cart_feature_coming': '장바구니 기능은 준비 중입니다',
      'product_desc_talisman': '전통적인 방법으로 제작된 부적입니다. 행운과 복을 가져다줍니다.',
      'product_desc_accessory': '운세를 높여주는 특별한 액세서리입니다. 매일 착용하시면 효과가 있습니다.',
      'product_desc_service': '전문가가 직접 분석해드리는 프리미엄 서비스입니다. 상세한 리포트를 제공합니다.',
      // Coming Soon
      'coming_soon': '추가 업데이트 예정',
      'coming_soon_desc': '전문가 상담 기능은 곧 추가될 예정입니다.\n조금만 기다려주세요!',
      'shop_coming_soon_desc': '운세 관련 상품 쇼핑 기능은 곧 추가될 예정입니다.\n조금만 기다려주세요!',
      // Analysis Result Screen
      'analysis_complete': '분석 완료!',
      'confidence': '신뢰도',
      'analysis_result': '분석 결과',
      'detailed_info': '상세 정보',
      'share_feature_coming': '공유 기능은 준비 중입니다',
      // Common
      'photo_guide': '촬영 가이드',
      'bright_light': '밝은 조명',
      'bright_light_desc': '얼굴이 잘 보이도록 밝은 곳에서 촬영하세요',
      'front_view': '정면 촬영',
      'front_view_desc': '얼굴이 정면으로 보이도록 촬영하세요',
      'close_distance': '가까운 거리',
      'close_distance_desc': '얼굴이 화면에 크게 보이도록 가까이에서 촬영하세요',
      'natural_expression': '자연스러운 표정',
      'natural_expression_desc': '자연스럽고 편안한 표정으로 촬영하세요',
      'privacy_notice': '※ 개인정보 보호를 위해 촬영된 사진은 분석 후 즉시 삭제됩니다.',
      'error_occurred': '분석 중 오류가 발생했습니다',
      'palm_guide': '손금 촬영 가이드',
      'open_palm': '손바닥 펴기',
      'open_palm_desc': '손바닥을 활짝 펴서 손금이 잘 보이도록 하세요',
      'clear_lines': '선명한 손금',
      'clear_lines_desc': '손금 선이 선명하게 보이도록 초점을 맞추세요',
    },
    'en': {
      'app_title': '✨ The God of Fortune: Saju Reading',
      'home': 'Home',
      'my_reports': 'Reports',
      'shop': 'Shop',
      'consultation': 'Consult',
      'ai_analysis': 'AI Analysis',
      'daily_fortune': 'Daily Fortune',
      'personality': 'Personality',
      'face_reading': 'Face',
      'face_reading_subtitle': 'AI Face Analysis',
      'palm_reading': 'Palm',
      'palm_reading_subtitle': 'AI Palm Reading',
      'saju': 'Four Pillars',
      'saju_subtitle': 'Birth Analysis',
      'tarot': 'Tarot',
      'tarot_subtitle': 'Card Reading',
      'zodiac': 'Zodiac',
      'zodiac_subtitle': 'Star Sign',
      'mbti': 'MBTI',
      'mbti_subtitle': 'Personality Type',
      'today_fortune': 'Today',
      'today_fortune_subtitle': 'Daily Luck',
      'disclaimer': '※ Results are for reference. Your choices matter most.',
      'promo_title': '🎉 Special Offer!',
      'promo_subtitle': '₩48,000 for 1 Year',
      'promo_highlight': '',
      'promo_free_trial_line1': 'No Registration',
      'promo_free_trial_line2': '2 Free Trials',
      'promo_description': 'Sign up now for 12-month\npremium service at special price!',
      'promo_button': 'Get Started',
      // Signup
      'signup_cta_title': 'Sign Up',
      'signup_cta_subtitle': 'Start 12-Month Premium Service',
      'signup_title': 'Sign Up',
      'signup_welcome': 'Welcome!',
      'signup_subtitle': 'Start your 12-month premium service',
      'name_label': 'Name',
      'name_hint': 'Enter your name',
      'name_required': 'Please enter your name',
      'gender_label': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'birthdate_label': 'Birthdate (Solar)',
      'birthdate_hint': 'YYYY-MM-DD',
      'birthdate_required': 'Please select your birthdate',
      'email_label': 'Email',
      'email_hint': 'example@email.com',
      'email_required': 'Please enter your email',
      'email_invalid': 'Invalid email format',
      'payment_title': 'Payment',
      'payment_plan': '1-Year Premium Service',
      'payment_price': '₩48,000',
      'select_payment_method': 'Select payment method',
      'bank_transfer': 'Bank Transfer',
      'kakao_pay': 'Kakao Pay',
      'naver_pay': 'Naver Pay',
      'mobile_payment': 'Mobile',
      'signup_button': 'Sign Up',
      'select_gender_error': 'Please select gender',
      'select_payment_error': 'Please select payment method',
      'signup_success_title': 'Complete!',
      'signup_success_message': 'Registration complete! Enjoy 12-month premium service!',
      'confirm': 'Confirm',
      'error': 'Error',
      'global_service': '🌍 Global Service',
      'language': 'Language',
      // Today Fortune Screen
      'today_fortune_title': '☀️ Today\'s Fortune',
      'overall_fortune': 'Overall',
      'love_fortune': 'Love',
      'money_fortune': 'Money',
      'health_fortune': 'Health',
      'work_fortune': 'Work',
      'todays_luck': '🍀 Today\'s Luck',
      'lucky_number': 'Lucky Number',
      'lucky_color': 'Lucky Color',
      'lucky_item': 'Lucky Item',
      'todays_advice': 'Today\'s Advice',
      'refresh': 'Refresh',
      // Zodiac Screen
      'zodiac_title': '⭐ Zodiac Fortune',
      'select_zodiac': 'Select Your Zodiac Sign',
      'select_zodiac_desc': 'Find your zodiac based on your birthday',
      'choose_again': 'Choose Again',
      'todays_fortune_detail': 'Today\'s Fortune',
      'personality_traits': 'Personality Traits',
      'lucky_elements': 'Lucky Elements',
      'lucky_day': 'Lucky Day',
      // MBTI Screen
      'mbti_title': '🧠 MBTI Analysis',
      'select_mbti': 'Select Your MBTI Type',
      'select_mbti_desc': 'Choose from 16 personality types',
      'analysts': 'Analysts',
      'diplomats': 'Diplomats',
      'sentinels': 'Sentinels',
      'explorers': 'Explorers',
      'description': 'Description',
      'traits': 'Traits',
      'strengths': 'Strengths',
      'career_suggestions': 'Career Suggestions',
      // Face Analysis Screen
      'face_analysis_title': 'Face Reading',
      'face_analysis_desc': 'AI analyzes your face photo\nfor physiognomy reading',
      'take_photo': 'Take Photo',
      'upload_photo': 'Upload Photo',
      'analyzing': 'Analyzing...',
      // Palm Reading Screen
      'palm_reading_title': 'Palm Reading',
      'palm_reading_desc': 'AI analyzes your palm photo\nto reveal your destiny',
      // Saju Screen
      'saju_title': 'Four Pillars',
      'saju_desc': 'Enter your birth date and time\nto check your Saju',
      'birth_date': 'Birth Date',
      'birth_time': 'Birth Time',
      'gender': 'Gender',
      'analyze_saju': 'Analyze Saju',
      'enter_birth_info': 'Enter your birth date',
      // Tarot Screen
      'tarot_title': 'Tarot Cards',
      'tarot_desc': 'Think of your question\nand select cards',
      'tarot_reading': 'Tarot Card Reading',
      'tarot_reading_desc': 'Read the future with tarot cards',
      'question': 'Question',
      'question_placeholder': 'e.g., How is my love life?',
      'enter_question': 'Please enter a question',
      'card_count': 'Number of Cards',
      'one_card': 'One Card',
      'three_cards': 'Three Cards',
      'five_cards': 'Five Cards',
      'start_reading': 'Start Reading',
      'drawing_cards': 'Drawing cards...',
      'tarot_guide': 'Tarot Reading Guide',
      'one_card_desc': 'Answer to a simple question',
      'three_cards_desc': 'Past-Present-Future flow',
      'five_cards_desc': 'Complex situation analysis',
      'select_cards': 'Select Cards',
      'card_reading': 'Card Reading',
      // Shop Screen
      'category_all': 'All',
      'category_talisman': 'Talisman',
      'category_accessory': 'Accessory',
      'category_service': 'Service',
      'product_detail': 'Product Detail',
      'product_description': 'Description',
      'reviews': 'reviews',
      'add_to_cart': 'Add to Cart',
      'added_to_cart': 'added to cart',
      'view_cart': 'View',
      'cart_feature_coming': 'Cart feature is coming soon',
      'product_desc_talisman': 'Traditional talisman crafted with care. Brings luck and fortune.',
      'product_desc_accessory': 'Special accessory to boost your fortune. Wear it daily for best effect.',
      'product_desc_service': 'Premium service with expert analysis. Detailed report provided.',
      // Coming Soon
      'coming_soon': 'Coming Soon',
      'coming_soon_desc': 'Expert consultation feature will be added soon.\nPlease stay tuned!',
      'shop_coming_soon_desc': 'Fortune-related product shopping feature will be added soon.\nPlease stay tuned!',
      // Analysis Result Screen
      'analysis_complete': 'Analysis Complete!',
      'confidence': 'Confidence',
      'analysis_result': 'Analysis Result',
      'detailed_info': 'Detailed Information',
      'share_feature_coming': 'Share feature coming soon',
      // Common
      'photo_guide': 'Photo Guide',
      'bright_light': 'Bright Lighting',
      'bright_light_desc': 'Take photos in a well-lit area so your face is clearly visible',
      'front_view': 'Front View',
      'front_view_desc': 'Position your face directly facing the camera',
      'close_distance': 'Close Distance',
      'close_distance_desc': 'Get close so your face fills the frame',
      'natural_expression': 'Natural Expression',
      'natural_expression_desc': 'Keep a relaxed and natural expression',
      'privacy_notice': '※ Photos are deleted immediately after analysis for privacy protection.',
      'error_occurred': 'An error occurred during analysis',
      'palm_guide': 'Palm Reading Guide',
      'open_palm': 'Open Palm',
      'open_palm_desc': 'Spread your palm wide so lines are clearly visible',
      'clear_lines': 'Clear Lines',
      'clear_lines_desc': 'Focus on making palm lines sharp and visible',
    },
    'zh': {
      'app_title': '✨ 命运之神：八字命理解析',
      'home': '首页',
      'my_reports': '报告',
      'shop': '商店',
      'consultation': '咨询',
      'ai_analysis': 'AI分析',
      'daily_fortune': '每日运势',
      'personality': '性格分析',
      'face_reading': '面相',
      'face_reading_subtitle': 'AI面相分析',
      'palm_reading': '手相',
      'palm_reading_subtitle': 'AI手相分析',
      'saju': '四柱',
      'saju_subtitle': '生辰分析',
      'tarot': '塔罗',
      'tarot_subtitle': '塔罗占卜',
      'zodiac': '星座',
      'zodiac_subtitle': '星座运势',
      'mbti': 'MBTI',
      'mbti_subtitle': '性格类型',
      'today_fortune': '今日',
      'today_fortune_subtitle': '今日运势',
      'disclaimer': '※ 结果仅供参考。您的选择最重要。',
      'promo_title': '🎉 特别优惠！',
      'promo_subtitle': '₩48,000元 1年',
      'promo_highlight': '',
      'promo_free_trial_line1': '无需注册',
      'promo_free_trial_line2': '2次免费体验',
      'promo_description': '现在注册享12个月\n高级服务特惠价！',
      'promo_button': '立即开始',
      // Signup
      'signup_cta_title': '注册',
      'signup_cta_subtitle': '开始12个月高级服务',
      'signup_title': '注册',
      'signup_welcome': '欢迎！',
      'signup_subtitle': '开始您的12个月高级服务',
      'name_label': '姓名',
      'name_hint': '请输入姓名',
      'name_required': '请输入姓名',
      'gender_label': '性别',
      'male': '男',
      'female': '女',
      'birthdate_label': '出生日期（阳历）',
      'birthdate_hint': 'YYYY-MM-DD',
      'birthdate_required': '请选择出生日期',
      'email_label': '邮箱',
      'email_hint': 'example@email.com',
      'email_required': '请输入邮箱',
      'email_invalid': '邮箱格式无效',
      'payment_title': '付款',
      'payment_plan': '12个月高级服务',
      'payment_price': '₩24,000',
      'select_payment_method': '选择付款方式',
      'bank_transfer': '银行转账',
      'kakao_pay': 'Kakao Pay',
      'naver_pay': 'Naver Pay',
      'mobile_payment': '手机支付',
      'signup_button': '注册',
      'select_gender_error': '请选择性别',
      'select_payment_error': '请选择付款方式',
      'signup_success_title': '完成！',
      'signup_success_message': '注册完成！享受12个月高级服务！',
      'confirm': '确认',
      'error': '错误',
      'global_service': '🌍 全球服务',
      'language': '语言',
      // Today Fortune Screen
      'today_fortune_title': '☀️ 今日运势',
      'overall_fortune': '综合运势',
      'love_fortune': '爱情运',
      'money_fortune': '财运',
      'health_fortune': '健康运',
      'work_fortune': '事业运',
      'todays_luck': '🍀 今日幸运',
      'lucky_number': '幸运数字',
      'lucky_color': '幸运颜色',
      'lucky_item': '幸运物品',
      'todays_advice': '今日建议',
      'refresh': '刷新',
      // Zodiac Screen
      'zodiac_title': '⭐ 星座运势',
      'select_zodiac': '选择您的星座',
      'select_zodiac_desc': '根据您的生日找到您的星座',
      'choose_again': '重新选择',
      'todays_fortune_detail': '今日运势',
      'personality_traits': '性格特征',
      'lucky_elements': '幸运元素',
      'lucky_day': '幸运日',
      // MBTI Screen
      'mbti_title': '🧠 MBTI性格分析',
      'select_mbti': '选择您的MBTI类型',
      'select_mbti_desc': '从16种性格类型中选择一种',
      'analysts': '分析家',
      'diplomats': '外交官',
      'sentinels': '守护者',
      'explorers': '探险家',
      'description': '性格描述',
      'traits': '性格特征',
      'strengths': '优势',
      'career_suggestions': '推荐职业',
      // Face Analysis Screen
      'face_analysis_title': '面相分析',
      'face_analysis_desc': 'AI分析您的面相照片\n解读您的相貌',
      'take_photo': '拍摄照片',
      'upload_photo': '上传照片',
      'analyzing': '分析中...',
      // Palm Reading Screen
      'palm_reading_title': '手相分析',
      'palm_reading_desc': 'AI分析您的手相照片\n揭示您的命运',
      // Saju Screen
      'saju_title': '四柱八字',
      'saju_desc': '输入您的生辰时间\n查看您的八字',
      'birth_date': '出生日期',
      'birth_time': '出生时间',
      'gender': '性别',
      'analyze_saju': '分析八字',
      'enter_birth_info': '请输入出生日期',
      // Tarot Screen
      'tarot_title': '塔罗牌',
      'tarot_desc': '思考您的问题\n选择塔罗牌',
      'tarot_reading': '塔罗牌占卜',
      'tarot_reading_desc': '用塔罗牌解读未来',
      'question': '问题',
      'question_placeholder': '例如：我的爱情运势如何？',
      'enter_question': '请输入问题',
      'card_count': '卡牌数量',
      'one_card': '一张',
      'three_cards': '三张',
      'five_cards': '五张',
      'start_reading': '开始占卜',
      'drawing_cards': '正在抽取卡牌...',
      'tarot_guide': '塔罗占卜指南',
      'one_card_desc': '简单问题的答案',
      'three_cards_desc': '过去-现在-未来流向',
      'five_cards_desc': '复杂情况分析',
      'select_cards': '选择卡牌',
      'card_reading': '卡牌解读',
      // Shop Screen
      'category_all': '全部',
      'category_talisman': '符咲',
      'category_accessory': '配饰',
      'category_service': '服务',
      'product_detail': '产品详情',
      'product_description': '产品说明',
      'reviews': '评论',
      'add_to_cart': '加入购物车',
      'added_to_cart': '已加入购物车',
      'view_cart': '查看',
      'cart_feature_coming': '购物车功能即将推出',
      'product_desc_talisman': '传统工艺制作的符咲。带来幸运和福气。',
      'product_desc_accessory': '提升运势的特别配饰。每天佩戴效果更佳。',
      'product_desc_service': '专家亲自分析的高端服务。提供详细报告。',
      // Coming Soon
      'coming_soon': '即将推出',
      'coming_soon_desc': '专家咨询功能即将添加。\n请期待！',
      'shop_coming_soon_desc': '命运相关产品购物功能即将添加。\n请期待！',
      // Analysis Result Screen
      'analysis_complete': '分析完成！',
      'confidence': '置信度',
      'analysis_result': '分析结果',
      'detailed_info': '详细信息',
      'share_feature_coming': '分享功能即将推出',
      // Common
      'photo_guide': '拍摄指南',
      'bright_light': '明亮光线',
      'bright_light_desc': '在光线充足的地方拍摄，使面部清晰可见',
      'front_view': '正面拍摄',
      'front_view_desc': '将脸部正对摄像头',
      'close_distance': '近距离',
      'close_distance_desc': '靠近拍摄，使面部充满画面',
      'natural_expression': '自然表情',
      'natural_expression_desc': '保持放松和自然的表情',
      'privacy_notice': '※ 为保护隐私，照片在分析后立即删除。',
      'error_occurred': '分析过程中发生错误',
      'palm_guide': '手相拍摄指南',
      'open_palm': '张开手掌',
      'open_palm_desc': '张开手掌，使掌纹清晰可见',
      'clear_lines': '清晰纹路',
      'clear_lines_desc': '对焦使掌纹线条清晰锐利',
    },
    'ja': {
      'app_title': '✨ 運命の神：四柱推命の鑑定',
      'home': 'ホーム',
      'my_reports': 'レポート',
      'shop': 'ショップ',
      'consultation': '相談',
      'ai_analysis': 'AI分析',
      'daily_fortune': '今日の運勢',
      'personality': '性格分析',
      'face_reading': '人相',
      'face_reading_subtitle': 'AI人相分析',
      'palm_reading': '手相',
      'palm_reading_subtitle': 'AI手相分析',
      'saju': '四柱',
      'saju_subtitle': '生年月日分析',
      'tarot': 'タロット',
      'tarot_subtitle': 'タロット占い',
      'zodiac': '星座',
      'zodiac_subtitle': '星座占い',
      'mbti': 'MBTI',
      'mbti_subtitle': '性格タイプ',
      'today_fortune': '今日',
      'today_fortune_subtitle': '今日の運',
      'disclaimer': '※ 結果は参考用です。あなたの選択が最も重要です。',
      'promo_title': '🎉 特別オファー！',
      'promo_subtitle': '₩48,000円 1年間',
      'promo_highlight': '',
      'promo_free_trial_line1': '会員登録不要',
      'promo_free_trial_line2': '2回無料体験',
      'promo_description': '今登録して12ヶ月\nプレミアムサービスを特別価格で！',
      'promo_button': '今すぐ始める',
      // Signup
      'signup_cta_title': '会員登録',
      'signup_cta_subtitle': '12ヶ月プレミアムサービスを開始',
      'signup_title': '会員登録',
      'signup_welcome': 'ようこそ！',
      'signup_subtitle': '12ヶ月プレミアムサービスを開始',
      'name_label': '名前',
      'name_hint': '名前を入力',
      'name_required': '名前を入力してください',
      'gender_label': '性別',
      'male': '男性',
      'female': '女性',
      'birthdate_label': '生年月日（太陽暦）',
      'birthdate_hint': 'YYYY-MM-DD',
      'birthdate_required': '生年月日を選択してください',
      'email_label': 'メール',
      'email_hint': 'example@email.com',
      'email_required': 'メールを入力してください',
      'email_invalid': 'メール形式が無効です',
      'payment_title': '決済',
      'payment_plan': '12ヶ月プレミアムサービス',
      'payment_price': '₩24,000',
      'select_payment_method': '決済方法を選択',
      'bank_transfer': '銀行振込',
      'kakao_pay': 'Kakao Pay',
      'naver_pay': 'Naver Pay',
      'mobile_payment': '携帯決済',
      'signup_button': '登録',
      'select_gender_error': '性別を選択してください',
      'select_payment_error': '決済方法を選択してください',
      'signup_success_title': '完了！',
      'signup_success_message': '登録完了！12ヶ月プレミアムサービスをお楽しみください！',
      'confirm': '確認',
      'error': 'エラー',
      'global_service': '🌍 グローバル',
      'language': '言語',
      // Today Fortune Screen
      'today_fortune_title': '☀️ 今日の運勢',
      'overall_fortune': '総合運',
      'love_fortune': '恋愛運',
      'money_fortune': '金運',
      'health_fortune': '健康運',
      'work_fortune': '仕事運',
      'todays_luck': '🍀 今日のラッキー',
      'lucky_number': 'ラッキーナンバー',
      'lucky_color': 'ラッキーカラー',
      'lucky_item': 'ラッキーアイテム',
      'todays_advice': '今日のアドバイス',
      'refresh': '更新',
      // Zodiac Screen
      'zodiac_title': '⭐ 星座占い',
      'select_zodiac': 'あなたの星座を選択',
      'select_zodiac_desc': '誕生日から星座を見つけましょう',
      'choose_again': '再選択',
      'todays_fortune_detail': '今日の運勢',
      'personality_traits': '性格の特徴',
      'lucky_elements': 'ラッキー要素',
      'lucky_day': 'ラッキーデー',
      // MBTI Screen
      'mbti_title': '🧠 MBTI性格分析',
      'select_mbti': 'あなたのMBTIタイプを選択',
      'select_mbti_desc': '16の性格タイプから選択',
      'analysts': '分析家',
      'diplomats': '外交官',
      'sentinels': '番人',
      'explorers': '探検家',
      'description': '性格説明',
      'traits': '性格特徴',
      'strengths': '強み',
      'career_suggestions': 'おすすめの職業',
      // Face Analysis Screen
      'face_analysis_title': '人相分析',
      'face_analysis_desc': 'AIが顔写真を分析して\n人相を読み取ります',
      'take_photo': '写真撮影',
      'upload_photo': '写真アップロード',
      'analyzing': '分析中...',
      // Palm Reading Screen
      'palm_reading_title': '手相占い',
      'palm_reading_desc': 'AIが手相写真を分析して\n運命を読み取ります',
      // Saju Screen
      'saju_title': '四柱推命',
      'saju_desc': '生年月日と時間を入力して\n四柱を確認',
      'birth_date': '生年月日',
      'birth_time': '生まれた時間',
      'gender': '性別',
      'analyze_saju': '四柱分析',
      'enter_birth_info': '生年月日を入力',
      // Tarot Screen
      'tarot_title': 'タロットカード',
      'tarot_desc': '質問を考えながら\nカードを選択',
      'tarot_reading': 'タロット占い',
      'tarot_reading_desc': 'タロットカードで未来を読む',
      'question': '質問',
      'question_placeholder': '例：私の恋愛運はどうですか？',
      'enter_question': '質問を入力してください',
      'card_count': 'カード枚数',
      'one_card': '1枚',
      'three_cards': '3枚',
      'five_cards': '5枚',
      'start_reading': 'タロット占い開始',
      'drawing_cards': 'カードを引いています...',
      'tarot_guide': 'タロット占いガイド',
      'one_card_desc': '簡単な質問への答え',
      'three_cards_desc': '過去-現在-未来の流れ',
      'five_cards_desc': '複雑な状況の分析',
      'select_cards': 'カード選択',
      'card_reading': 'カード解釈',
      // Shop Screen
      'category_all': '全て',
      'category_talisman': 'お守り',
      'category_accessory': 'アクセサリー',
      'category_service': 'サービス',
      'product_detail': '商品詳細',
      'product_description': '商品説明',
      'reviews': 'レビュー',
      'add_to_cart': 'カートに入れる',
      'added_to_cart': 'カートに追加しました',
      'view_cart': '見る',
      'cart_feature_coming': 'カート機能は準備中です',
      'product_desc_talisman': '伝統的な方法で作られたお守りです。幸運と福をもたらします。',
      'product_desc_accessory': '運勢を高める特別なアクセサリーです。毎日着用すると効果があります。',
      'product_desc_service': '専門家が直接分析するプレミアムサービスです。詳細なレポートを提供します。',
      // Coming Soon
      'coming_soon': '追加予定',
      'coming_soon_desc': '専門家相談機能は近日中に追加されます。\nもうしばらくお待ちください！',
      'shop_coming_soon_desc': '運勢関連商品ショッピング機能は近日中に追加されます。\nもうしばらくお待ちください！',
      // Analysis Result Screen
      'analysis_complete': '分析完了！',
      'confidence': '信頼度',
      'analysis_result': '分析結果',
      'detailed_info': '詳細情報',
      'share_feature_coming': '共有機能は準備中です',
      // Common
      'photo_guide': '撮影ガイド',
      'bright_light': '明るい照明',
      'bright_light_desc': '顔がよく見えるように明るい場所で撮影してください',
      'front_view': '正面撮影',
      'front_view_desc': '顔が正面に見えるように撮影してください',
      'close_distance': '近い距離',
      'close_distance_desc': '顔が画面に大きく映るように近くで撮影してください',
      'natural_expression': '自然な表情',
      'natural_expression_desc': '自然でリラックスした表情で撮影してください',
      'privacy_notice': '※ プライバシー保護のため、撮影された写真は分析後すぐに削除されます。',
      'error_occurred': '分析中にエラーが発生しました',
      'palm_guide': '手相撮影ガイド',
      'open_palm': '手のひらを開く',
      'open_palm_desc': '手相がよく見えるように手のひらを広げてください',
      'clear_lines': '鮮明な線',
      'clear_lines_desc': '手相の線が鮮明に見えるようにフォーカスを合わせてください',
    },
    'vi': {
      'app_title': '✨ Thần Vận Mệnh: Xem Tứ Trụ',
      'home': 'Trang chủ',
      'my_reports': 'Báo cáo',
      'shop': 'Cửa hàng',
      'consultation': 'Tư vấn',
      'ai_analysis': 'AI Phân tích',
      'daily_fortune': 'Vận hàng ngày',
      'personality': 'Tính cách',
      'face_reading': 'Tướng mặt',
      'face_reading_subtitle': 'AI phân tích',
      'palm_reading': 'Chỉ tay',
      'palm_reading_subtitle': 'AI xem chỉ',
      'saju': 'Tứ trụ',
      'saju_subtitle': 'Phân tích sinh',
      'tarot': 'Tarot',
      'tarot_subtitle': 'Bói bài',
      'zodiac': 'Cung hoàng đạo',
      'zodiac_subtitle': 'Vận cung',
      'mbti': 'MBTI',
      'mbti_subtitle': 'Loại tính cách',
      'today_fortune': 'Hôm nay',
      'today_fortune_subtitle': 'Vận ngày',
      'disclaimer': '※ Kết quả chỉ tham khảo. Lựa chọn của bạn quan trọng nhất.',
      'promo_title': '🎉 Ưu đãi đặc biệt!',
      'promo_subtitle': '₩48,000 cho 1 năm',
      'promo_highlight': '',
      'promo_free_trial_line1': 'Không cần đăng ký',
      'promo_free_trial_line2': '2 lần dùng thử miễn phí',
      'promo_description': 'Đăng ký ngay cho 12 tháng\ndịch vụ cao cấp giá ưu đãi!',
      'promo_button': 'Bắt đầu',
      // Signup
      'signup_cta_title': 'Đăng ký',
      'signup_cta_subtitle': 'Bắt đầu 12 tháng dịch vụ cao cấp',
      'signup_title': 'Đăng ký',
      'signup_welcome': 'Chào mừng!',
      'signup_subtitle': 'Bắt đầu 12 tháng dịch vụ cao cấp',
      'name_label': 'Tên',
      'name_hint': 'Nhập tên',
      'name_required': 'Vui lòng nhập tên',
      'gender_label': 'Giới tính',
      'male': 'Nam',
      'female': 'Nữ',
      'birthdate_label': 'Ngày sinh (Dương lịch)',
      'birthdate_hint': 'YYYY-MM-DD',
      'birthdate_required': 'Vui lòng chọn ngày sinh',
      'email_label': 'Email',
      'email_hint': 'example@email.com',
      'email_required': 'Vui lòng nhập email',
      'email_invalid': 'Định dạng email không hợp lệ',
      'payment_title': 'Thanh toán',
      'payment_plan': '12 tháng dịch vụ cao cấp',
      'payment_price': '₩24,000',
      'select_payment_method': 'Chọn phương thức thanh toán',
      'bank_transfer': 'Chuyển khoản',
      'kakao_pay': 'Kakao Pay',
      'naver_pay': 'Naver Pay',
      'mobile_payment': 'Di động',
      'signup_button': 'Đăng ký',
      'select_gender_error': 'Vui lòng chọn giới tính',
      'select_payment_error': 'Vui lòng chọn phương thức thanh toán',
      'signup_success_title': 'Hoàn tất!',
      'signup_success_message': 'Đăng ký hoàn tất! Tận hưởng 12 tháng dịch vụ cao cấp!',
      'confirm': 'Xác nhận',
      'error': 'Lỗi',
      'global_service': '🌍 Toàn cầu',
      'language': 'Ngôn ngữ',
      // Today Fortune Screen
      'today_fortune_title': '☀️ Vận Hôm Nay',
      'overall_fortune': 'Tổng quan',
      'love_fortune': 'Tình yêu',
      'money_fortune': 'Tài chính',
      'health_fortune': 'Sức khỏe',
      'work_fortune': 'Công việc',
      'todays_luck': '🍀 May Mắn Hôm Nay',
      'lucky_number': 'Số may mắn',
      'lucky_color': 'Màu may mắn',
      'lucky_item': 'Vật phẩm may mắn',
      'todays_advice': 'Lời khuyên',
      'refresh': 'Làm mới',
      // Zodiac Screen
      'zodiac_title': '⭐ Cung Hoàng Đạo',
      'select_zodiac': 'Chọn cung của bạn',
      'select_zodiac_desc': 'Tìm cung hoàng đạo theo ngày sinh',
      'choose_again': 'Chọn lại',
      'todays_fortune_detail': 'Vận hôm nay',
      'personality_traits': 'Đặc điểm tính cách',
      'lucky_elements': 'Yếu tố may mắn',
      'lucky_day': 'Ngày may mắn',
      // MBTI Screen
      'mbti_title': '🧠 Phân Tích MBTI',
      'select_mbti': 'Chọn loại MBTI',
      'select_mbti_desc': 'Chọn từ 16 loại tính cách',
      'analysts': 'Nhà phân tích',
      'diplomats': 'Nhà ngoại giao',
      'sentinels': 'Người bảo vệ',
      'explorers': 'Nhà thám hiểm',
      'description': 'Mô tả',
      'traits': 'Đặc điểm',
      'strengths': 'Điểm mạnh',
      'career_suggestions': 'Nghề nghiệp',
      // Face Analysis Screen
      'face_analysis_title': 'Xem Tướng Mặt',
      'face_analysis_desc': 'AI phân tích ảnh khuôn mặt\nđể xem tướng',
      'take_photo': 'Chụp ảnh',
      'upload_photo': 'Tải ảnh lên',
      'analyzing': 'Đang phân tích...',
      // Palm Reading Screen
      'palm_reading_title': 'Xem Chỉ Tay',
      'palm_reading_desc': 'AI phân tích ảnh lòng bàn tay\nđể xem vận mệnh',
      // Saju Screen
      'saju_title': 'Tứ Trụ',
      'saju_desc': 'Nhập ngày tháng năm sinh\nđể xem tứ trụ',
      'birth_date': 'Ngày sinh',
      'birth_time': 'Giờ sinh',
      'gender': 'Giới tính',
      'analyze_saju': 'Phân tích tứ trụ',
      'enter_birth_info': 'Nhập ngày sinh',
      // Tarot Screen
      'tarot_title': 'Bài Tarot',
      'tarot_desc': 'Suy nghĩ câu hỏi\nvà chọn bài',
      'tarot_reading': 'Đọc Bài Tarot',
      'tarot_reading_desc': 'Đọc tương lai với bài Tarot',
      'question': 'Câu hỏi',
      'question_placeholder': 'VD: Tình duyên của tôi như thế nào?',
      'enter_question': 'Vui lòng nhập câu hỏi',
      'card_count': 'Số lá bài',
      'one_card': 'Một lá',
      'three_cards': 'Ba lá',
      'five_cards': 'Năm lá',
      'start_reading': 'Bắt đầu đọc bài',
      'drawing_cards': 'Đang rút bài...',
      'tarot_guide': 'Hướng dẫn Tarot',
      'one_card_desc': 'Trả lời câu hỏi đơn giản',
      'three_cards_desc': 'Quá khứ-Hiện tại-Tương lai',
      'five_cards_desc': 'Phân tích tình huống phức tạp',
      'select_cards': 'Chọn bài',
      'card_reading': 'Giải bài',
      // Shop Screen
      'category_all': 'Tất cả',
      'category_talisman': 'Bùa',
      'category_accessory': 'Phụ kiện',
      'category_service': 'Dịch vụ',
      'product_detail': 'Chi tiết sản phẩm',
      'product_description': 'Mô tả',
      'reviews': 'đánh giá',
      'add_to_cart': 'Thêm vào giỏ',
      'added_to_cart': 'đã thêm vào giỏ',
      'view_cart': 'Xem',
      'cart_feature_coming': 'Tính năng giỏ hàng sắp ra mắt',
      'product_desc_talisman': 'Bùa truyền thống được chế tác cẩn thận. Mang lại may mắn và phúc lộc.',
      'product_desc_accessory': 'Phụ kiện đặc biệt tăng vận may. Đeo hàng ngày để có hiệu quả tốt nhất.',
      'product_desc_service': 'Dịch vụ cao cấp với phân tích chuyên gia. Cung cấp báo cáo chi tiết.',
      // Coming Soon
      'coming_soon': 'Sắp ra mắt',
      'coming_soon_desc': 'Tính năng tư vấn chuyên gia sẽ sớm được thêm vào.\nVui lòng chờ đợi!',
      'shop_coming_soon_desc': 'Tính năng mua sắm sản phẩm vận số sẽ sớm được thêm vào.\nVui lòng chờ đợi!',
      // Analysis Result Screen
      'analysis_complete': 'Phân tích hoàn tất!',
      'confidence': 'Độ tin cậy',
      'analysis_result': 'Kết quả phân tích',
      'detailed_info': 'Thông tin chi tiết',
      'share_feature_coming': 'Tính năng chia sẻ sắp ra mắt',
      // Common
      'photo_guide': 'Hướng dẫn chụp',
      'bright_light': 'Ánh sáng tốt',
      'bright_light_desc': 'Chụp ở nơi sáng để khuôn mặt rõ ràng',
      'front_view': 'Góc chính diện',
      'front_view_desc': 'Đặt mặt thẳng với camera',
      'close_distance': 'Khoảng cách gần',
      'close_distance_desc': 'Đến gần để mặt đầy khung hình',
      'natural_expression': 'Biểu cảm tự nhiên',
      'natural_expression_desc': 'Giữ biểu cảm thư giãn và tự nhiên',
      'privacy_notice': '※ Ảnh được xóa ngay sau phân tích để bảo vệ quyền riêng tư.',
      'error_occurred': 'Đã xảy ra lỗi trong quá trình phân tích',
      'palm_guide': 'Hướng dẫn xem chỉ tay',
      'open_palm': 'Mở bàn tay',
      'open_palm_desc': 'Mở rộng lòng bàn tay để đường chỉ rõ ràng',
      'clear_lines': 'Đường rõ nét',
      'clear_lines_desc': 'Lấy nét để đường chỉ tay sắc nét',
    },
    'th': {
      'app_title': '✨ เทพแห่งโชคชะตา: ดวงชะตา',
      'home': 'หน้าแรก',
      'my_reports': 'รายงาน',
      'shop': 'ร้านค้า',
      'consultation': 'ปรึกษา',
      'ai_analysis': 'AI วิเคราะห์',
      'daily_fortune': 'ดวงวันนี้',
      'personality': 'บุคลิก',
      'face_reading': 'ดูหน้า',
      'face_reading_subtitle': 'AI วิเคราะห์',
      'palm_reading': 'ดูมือ',
      'palm_reading_subtitle': 'AI ลายมือ',
      'saju': 'โหราศาสตร์',
      'saju_subtitle': 'วิเคราะห์เกิด',
      'tarot': 'ทาโรต์',
      'tarot_subtitle': 'ดูไพ่',
      'zodiac': 'ราศี',
      'zodiac_subtitle': 'ดวงราศี',
      'mbti': 'MBTI',
      'mbti_subtitle': 'ประเภทบุคลิก',
      'today_fortune': 'วันนี้',
      'today_fortune_subtitle': 'ดวงวันนี้',
      'disclaimer': '※ ผลเป็นข้อมูลอ้างอิง ทางเลือกของคุณสำคัญที่สุด',
      'promo_title': '🎉 ข้อเสนอพิเศษ!',
      'promo_subtitle': '₩48,000 สำหรับ 1 ปี',
      'promo_highlight': 'ฟรี 12 เดือน',
      'promo_description': 'สมัครตอนนี้\nฟรี 12 เดือน!',
      'promo_button': 'เริ่มเลย',
      'global_service': '🌍 ทั่วโลก',
      'language': 'ภาษา',
      // Today Fortune Screen
      'today_fortune_title': '☀️ ดวงวันนี้',
      'overall_fortune': 'โดยรวม',
      'love_fortune': 'ความรัก',
      'money_fortune': 'การเงิน',
      'health_fortune': 'สุขภาพ',
      'work_fortune': 'การงาน',
      'todays_luck': '🍀 โชคดีวันนี้',
      'lucky_number': 'เลขมงคล',
      'lucky_color': 'สีมงคล',
      'lucky_item': 'ของมงคล',
      'todays_advice': 'คำแนะนำ',
      'refresh': 'รีเฟรช',
      // Zodiac Screen
      'zodiac_title': '⭐ ดวงราศี',
      'select_zodiac': 'เลือกราศีของคุณ',
      'select_zodiac_desc': 'หาราศีของคุณตามวันเกิด',
      'choose_again': 'เลือกใหม่',
      'todays_fortune_detail': 'ดวงวันนี้',
      'personality_traits': 'ลักษณะนิสัย',
      'lucky_elements': 'องค์ประกอบมงคล',
      'lucky_day': 'วันมงคล',
      // MBTI Screen
      'mbti_title': '🧠 วิเคราะห์ MBTI',
      'select_mbti': 'เลือกประเภท MBTI',
      'select_mbti_desc': 'เลือกจาก 16 ประเภทบุคลิก',
      'analysts': 'นักวิเคราะห์',
      'diplomats': 'นักการทูต',
      'sentinels': 'ผู้พิทักษ์',
      'explorers': 'นักสำรวจ',
      'description': 'คำอธิบาย',
      'traits': 'ลักษณะ',
      'strengths': 'จุดแข็ง',
      'career_suggestions': 'อาชีพที่แนะนำ',
      // Face Analysis Screen
      'face_analysis_title': 'ดูหน้า',
      'face_analysis_desc': 'AI วิเคราะห์รูปใบหน้า\nเพื่อดูลักษณะ',
      'take_photo': 'ถ่ายรูป',
      'upload_photo': 'อัพโหลดรูป',
      'analyzing': 'กำลังวิเคราะห์...',
      // Palm Reading Screen
      'palm_reading_title': 'ดูลายมือ',
      'palm_reading_desc': 'AI วิเคราะห์รูปฝ่ามือ\nเพื่อดูโชคชะตา',
      // Saju Screen
      'saju_title': 'โหราศาสตร์',
      'saju_desc': 'ใส่วันเกิดและเวลา\nเพื่อดูดวง',
      'birth_date': 'วันเกิด',
      'birth_time': 'เวลาเกิด',
      'gender': 'เพศ',
      'male': 'ชาย',
      'female': 'หญิง',
      'analyze_saju': 'วิเคราะห์ดวง',
      'enter_birth_info': 'ใส่วันเกิด',
      // Tarot Screen
      'tarot_title': 'ทาโรต์',
      'tarot_desc': 'คิดคำถาม\nและเลือกไพ่',
      'tarot_reading': 'อ่านไพ่ทาโรต์',
      'tarot_reading_desc': 'อ่านอนาคตด้วยไพ่ทาโรต์',
      'question': 'คำถาม',
      'question_placeholder': 'เช่น: ชีวิตรักของฉันเป็นอย่างไร?',
      'enter_question': 'กรุณาใส่คำถาม',
      'card_count': 'จำนวนไพ่',
      'one_card': 'หนึ่งใบ',
      'three_cards': 'สามใบ',
      'five_cards': 'ห้าใบ',
      'start_reading': 'เริ่มอ่านไพ่',
      'drawing_cards': 'กำลังจั่วไพ่...',
      'tarot_guide': 'คู่มือทาโรต์',
      'one_card_desc': 'คำตอบสำหรับคำถามง่ายๆ',
      'three_cards_desc': 'อดีต-ปัจจุบัน-อนาคต',
      'five_cards_desc': 'วิเคราะห์สถานการณ์ซับซ้อน',
      'select_cards': 'เลือกไพ่',
      'card_reading': 'อ่านไพ่',
      // Common
      'photo_guide': 'คู่มือการถ่ายภาพ',
      'bright_light': 'แสงสว่าง',
      'bright_light_desc': 'ถ่ายในที่สว่างเพื่อให้เห็นใบหน้าชัดเจน',
      'front_view': 'มุมหน้าตรง',
      'front_view_desc': 'ตั้งหน้าตรงกับกล้อง',
      'close_distance': 'ระยะใกล้',
      'close_distance_desc': 'เข้าใกล้เพื่อให้ใบหน้าเต็มกรอบ',
      'natural_expression': 'สีหน้าธรรมชาติ',
      'natural_expression_desc': 'รักษาสีหน้าผ่อนคลายและธรรมชาติ',
      'privacy_notice': '※ รูปถูกลบทันทีหลังวิเคราะห์เพื่อปกป้องความเป็นส่วนตัว',
      'error_occurred': 'เกิดข้อผิดพลาดระหว่างการวิเคราะห์',
      'palm_guide': 'คู่มือดูลายมือ',
      'open_palm': 'แบมือ',
      'open_palm_desc': 'แบฝ่ามือให้กว้างเพื่อเห็นเส้นชัดเจน',
      'clear_lines': 'เส้นชัด',
      'clear_lines_desc': 'โฟกัสให้เส้นลายมือชัดและคม',
    },
    'ar': {
      'app_title': '✨ إله الحظ: قراءة الأعمدة الأربعة',
      'home': 'الرئيسية',
      'my_reports': 'التقارير',
      'shop': 'المتجر',
      'consultation': 'استشارة',
      'ai_analysis': 'تحليل AI',
      'daily_fortune': 'حظ اليوم',
      'personality': 'الشخصية',
      'face_reading': 'الوجه',
      'face_reading_subtitle': 'تحليل AI',
      'palm_reading': 'الكف',
      'palm_reading_subtitle': 'قراءة AI',
      'saju': 'الأعمدة',
      'saju_subtitle': 'تحليل الميلاد',
      'tarot': 'التاروت',
      'tarot_subtitle': 'قراءة البطاقات',
      'zodiac': 'الأبراج',
      'zodiac_subtitle': 'حظ البرج',
      'mbti': 'MBTI',
      'mbti_subtitle': 'نوع الشخصية',
      'today_fortune': 'اليوم',
      'today_fortune_subtitle': 'حظ اليوم',
      'disclaimer': '※ النتائج للمرجع. اختياراتك هي الأهم.',
      'promo_title': '🎉 عرض خاص!',
      'promo_subtitle': '₩48,000 لمدة سنة',
      'promo_highlight': '',
      'promo_free_trial_line1': 'بدون تسجيل',
      'promo_free_trial_line2': 'تجربة مجانية مرتين',
      'promo_description': 'سجل الآن لمدة 12 شهراً\nخدمة مميزة بسعر خاص!',
      'promo_button': 'ابدأ الآن',
      // Signup
      'signup_cta_title': 'التسجيل',
      'signup_cta_subtitle': 'ابدأ خدمة 12 شهراً المميزة',
      'signup_title': 'التسجيل',
      'signup_welcome': 'أهلاً بك!',
      'signup_subtitle': 'ابدأ خدمتك المميزة لمدة 12 شهراً',
      'name_label': 'الاسم',
      'name_hint': 'أدخل الاسم',
      'name_required': 'الرجاء إدخال الاسم',
      'gender_label': 'الجنس',
      'male': 'ذكر',
      'female': 'أنثى',
      'birthdate_label': 'تاريخ الميلاد (ميلادي)',
      'birthdate_hint': 'YYYY-MM-DD',
      'birthdate_required': 'الرجاء اختيار تاريخ الميلاد',
      'email_label': 'البريد',
      'email_hint': 'example@email.com',
      'email_required': 'الرجاء إدخال البريد',
      'email_invalid': 'صيغة البريد غير صحيحة',
      'payment_title': 'الدفع',
      'payment_plan': 'خدمة 12 شهراً المميزة',
      'payment_price': '₩24,000',
      'select_payment_method': 'اختر طريقة الدفع',
      'bank_transfer': 'تحويل بنكي',
      'kakao_pay': 'Kakao Pay',
      'naver_pay': 'Naver Pay',
      'mobile_payment': 'الجوال',
      'signup_button': 'تسجيل',
      'select_gender_error': 'الرجاء اختيار الجنس',
      'select_payment_error': 'الرجاء اختيار طريقة الدفع',
      'signup_success_title': 'تم!',
      'signup_success_message': 'اكتمل التسجيل! استمتع بخدمة 12 شهراً المميزة!',
      'confirm': 'تأكيد',
      'error': 'خطأ',
      'global_service': '🌍 عالمي',
      'language': 'اللغة',
      // Today Fortune Screen
      'today_fortune_title': '☀️ حظ اليوم',
      'overall_fortune': 'الحظ العام',
      'love_fortune': 'الحب',
      'money_fortune': 'المال',
      'health_fortune': 'الصحة',
      'work_fortune': 'العمل',
      'todays_luck': '🍀 حظ اليوم',
      'lucky_number': 'الرقم المحظوظ',
      'lucky_color': 'اللون المحظوظ',
      'lucky_item': 'الشيء المحظوظ',
      'todays_advice': 'نصيحة اليوم',
      'refresh': 'تحديث',
      // Zodiac Screen
      'zodiac_title': '⭐ حظ الأبراج',
      'select_zodiac': 'اختر برجك',
      'select_zodiac_desc': 'ابحث عن برجك حسب تاريخ الميلاد',
      'choose_again': 'اختر مرة أخرى',
      'todays_fortune_detail': 'حظ اليوم',
      'personality_traits': 'سمات الشخصية',
      'lucky_elements': 'عناصر الحظ',
      'lucky_day': 'اليوم المحظوظ',
      // MBTI Screen
      'mbti_title': '🧠 تحليل MBTI',
      'select_mbti': 'اختر نوع MBTI',
      'select_mbti_desc': 'اختر من 16 نوع شخصية',
      'analysts': 'المحللون',
      'diplomats': 'الدبلوماسيون',
      'sentinels': 'الحراس',
      'explorers': 'المستكشفون',
      'description': 'الوصف',
      'traits': 'السمات',
      'strengths': 'نقاط القوة',
      'career_suggestions': 'المهن المقترحة',
      // Face Analysis Screen
      'face_analysis_title': 'قراءة الوجه',
      'face_analysis_desc': 'يحلل AI صورة وجهك\nلقراءة الملامح',
      'take_photo': 'التقط صورة',
      'upload_photo': 'رفع صورة',
      'analyzing': 'جاري التحليل...',
      // Palm Reading Screen
      'palm_reading_title': 'قراءة الكف',
      'palm_reading_desc': 'يحلل AI صورة كفك\nللكشف عن مصيرك',
      // Saju Screen
      'saju_title': 'الأعمدة الأربعة',
      'saju_desc': 'أدخل تاريخ ووقت ميلادك\nللتحقق من الأعمدة',
      'birth_date': 'تاريخ الميلاد',
      'birth_time': 'وقت الميلاد',
      'gender': 'الجنس',
      'analyze_saju': 'تحليل الأعمدة',
      'enter_birth_info': 'أدخل تاريخ الميلاد',
      // Tarot Screen
      'tarot_title': 'بطاقات التاروت',
      'tarot_desc': 'فكر في سؤالك\nواختر البطاقات',
      'tarot_reading': 'قراءة بطاقات التاروت',
      'tarot_reading_desc': 'اقرأ المستقبل ببطاقات التاروت',
      'question': 'السؤال',
      'question_placeholder': 'مثال: كيف حالتي العاطفية؟',
      'enter_question': 'يرجى إدخال سؤال',
      'card_count': 'عدد البطاقات',
      'one_card': 'بطاقة واحدة',
      'three_cards': 'ثلاث بطاقات',
      'five_cards': 'خمس بطاقات',
      'start_reading': 'ابدأ القراءة',
      'drawing_cards': 'جاري سحب البطاقات...',
      'tarot_guide': 'دليل قراءة التاروت',
      'one_card_desc': 'إجابة على سؤال بسيط',
      'three_cards_desc': 'الماضي-الحاضر-المستقبل',
      'five_cards_desc': 'تحليل موقف معقد',
      'select_cards': 'اختر البطاقات',
      'card_reading': 'قراءة البطاقات',
      // Shop Screen
      'category_all': 'الكل',
      'category_talisman': 'تعويذة',
      'category_accessory': 'إكسسوار',
      'category_service': 'خدمة',
      'product_detail': 'تفاصيل المنتج',
      'product_description': 'الوصف',
      'reviews': 'مراجعات',
      'add_to_cart': 'إضافة إلى السلة',
      'added_to_cart': 'تمت الإضافة إلى السلة',
      'view_cart': 'عرض',
      'cart_feature_coming': 'ميزة السلة قريبًا',
      'product_desc_talisman': 'تعويذة تقليدية مصنوعة بعناية. تجلب الحظ والثروة.',
      'product_desc_accessory': 'إكسسوار خاص لتعزيز حظك. ارتده يوميًا للحصول على أفضل تأثير.',
      'product_desc_service': 'خدمة متميزة مع تحليل الخبراء. يتم تقديم تقرير تفصيلي.',
      // Coming Soon
      'coming_soon': 'قريبًا',
      'coming_soon_desc': 'سيتم إضافة ميزة الاستشارة مع الخبراء قريبًا.\nيرجى الانتظار!',
      'shop_coming_soon_desc': 'سيتم إضافة ميزة تسوق المنتجات المتعلقة بالحظ قريبًا.\nيرجى الانتظار!',
      // Analysis Result Screen
      'analysis_complete': 'اكتمل التحليل！',
      'confidence': 'درجة الثقة',
      'analysis_result': 'نتيجة التحليل',
      'detailed_info': 'معلومات تفصيلية',
      'share_feature_coming': 'ميزة المشاركة قريبًا',
      // Common
      'photo_guide': 'دليل التصوير',
      'bright_light': 'إضاءة جيدة',
      'bright_light_desc': 'التقط الصور في مكان مضاء جيداً لرؤية الوجه بوضوح',
      'front_view': 'منظر أمامي',
      'front_view_desc': 'ضع وجهك مباشرة أمام الكاميرا',
      'close_distance': 'مسافة قريبة',
      'close_distance_desc': 'اقترب حتى يملأ وجهك الإطار',
      'natural_expression': 'تعبير طبيعي',
      'natural_expression_desc': 'احتفظ بتعبير مسترخي وطبيعي',
      'privacy_notice': '※ يتم حذف الصور فوراً بعد التحليل لحماية الخصوصية.',
      'error_occurred': 'حدث خطأ أثناء التحليل',
      'palm_guide': 'دليل قراءة الكف',
      'open_palm': 'افتح الكف',
      'open_palm_desc': 'افتح كفك على نطاق واسع لرؤية الخطوط بوضوح',
      'clear_lines': 'خطوط واضحة',
      'clear_lines_desc': 'ركز على جعل خطوط الكف حادة ومرئية',
    },
  };
}
